version: '3.10'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'  
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - main_network
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    networks:
      - main_network

  db:
    image: mysql:8.3.0
    restart: always
    environment:
    - MYSQL_DATABASE=main
    - MYSQL_ROOT_PASSWORD=Grigala27  # Set the root user's password here
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - main_network

networks:
  main_network:
      name: main_network
      driver: bridge

volumes:
  dbdata: