version: '3.10'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - admin_network
      - main_network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
    networks:
      - admin_network

  db:
    image: mysql:8.3.0
    restart: always
    environment:
    - MYSQL_DATABASE=admin
    - MYSQL_ROOT_PASSWORD=Grigala27  # Set the root user's password here
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - admin_network

networks:
  admin_network:
      name: admin_network
      driver: bridge
  main_network:
    external:
      name: main_network

volumes:
  dbdata: